"""empty message

Revision ID: 29f6e779e85b
Revises: 4485b9894170
Create Date: 2017-11-30 03:25:55.784641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f6e779e85b'
down_revision = '4485b9894170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm', sa.String(length=104), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirm')
    # ### end Alembic commands ###
